Java11 (#673)
* Specify Java 9

* Use latest AspectJ plugin version

* Update AspectJ to latest beta

* Updated pom.xml for Java 11

* Updated pom.xml for Java 11

* added TODO

* switch to aspect-maven-plugin fork with Java 11 support.

* Updated aspectj to latest

* Switched to io.starter fork of the aspectj-maven-plugin.

* aspectj compile fails on root module as there's no sources, ignore this error (for now)

* Updated JAXB dependency (com.sun.xml.bind package was removed in Java 11).

* Updated aspectj-maven-plugin dependency in module poms.

* Fixed incorrect import.

* Fixed: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: java.lang.NoClassDefFoundError: javax/sql/DataSource: javax.sql.DataSource
Added --add-module argument.

* Fixed: @CallerSensitive annotation removed.
Replaced with StackWalker (ref. https://bugs.openjdk.java.net/browse/JDK-8154203)
TODO: need to test the correct parent class is returned.

* Downgrade mockito (broke lots of tests)

* Fixed tests (JAXB formatting changed, elements on new lines)

* Added missing java.xml module

* --add-modules is incompatible with java8, but needed when we start building java11 binaries

* Replaced reflection/stackwalker magic with explicit passing of AuthenticationStrategy.

* Fix tests (JAXB formatting has changed).

* Emit Java8 binaries (for now).

* Output Java11 binaries.

* Jersey 2 32 (#691)

* Update Jersey to 2.32.

* Line up test assertions.

* Explicitly register jaxb handler with Jersey client (it's not autodiscovered like its server counterpart).

* * bump aspectj to 1.9.6
* skip aspectj generated field in thread safety check

* Removed forkCount.

* Use latest Java11 whois-build image.

Co-authored-by: Edward Shryane <eshryane@ripe.net>