Set SERVICE before constructing command line
Undefined SERVICE resulted in an empty -D option.
This was causing jetty freaking out because of
java.lang.IllegalArgumentException: key can't be empty